// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1qiQJM364JvqY6h7kgg6v2g1xVa37C_o',
    appId: '1:1047451737063:web:56ad416ce061df550cfb42',
    messagingSenderId: '1047451737063',
    projectId: 'peerlink-d7666',
    authDomain: 'peerlink-d7666.firebaseapp.com',
    storageBucket: 'peerlink-d7666.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0LKftuO9m8GHlaTsZ6VrLyqgygPT47Sc',
    appId: '1:1047451737063:android:f9aa7d987a23e56f0cfb42',
    messagingSenderId: '1047451737063',
    projectId: 'peerlink-d7666',
    storageBucket: 'peerlink-d7666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQr0M1Iw0BuEnM22yTeeuys7myWZLDY38',
    appId: '1:1047451737063:ios:9d8d832ccf79330e0cfb42',
    messagingSenderId: '1047451737063',
    projectId: 'peerlink-d7666',
    storageBucket: 'peerlink-d7666.firebasestorage.app',
    iosBundleId: 'com.example.peerlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQr0M1Iw0BuEnM22yTeeuys7myWZLDY38',
    appId: '1:1047451737063:ios:9d8d832ccf79330e0cfb42',
    messagingSenderId: '1047451737063',
    projectId: 'peerlink-d7666',
    storageBucket: 'peerlink-d7666.firebasestorage.app',
    iosBundleId: 'com.example.peerlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1qiQJM364JvqY6h7kgg6v2g1xVa37C_o',
    appId: '1:1047451737063:web:48cd29275ade4ea10cfb42',
    messagingSenderId: '1047451737063',
    projectId: 'peerlink-d7666',
    authDomain: 'peerlink-d7666.firebaseapp.com',
    storageBucket: 'peerlink-d7666.firebasestorage.app',
  );
}
